// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxMOWaAH86WBhDlpm6xKlOjC3BuJqzzrc',
    appId: '1:613422672008:web:b2ccf3a963676d8a25573d',
    messagingSenderId: '613422672008',
    projectId: 'xlcdapp',
    authDomain: 'xlcdapp.firebaseapp.com',
    storageBucket: 'xlcdapp.appspot.com',
    measurementId: 'G-86Z986S59R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrgu8j4J6t0sd_M090uYL0JKJW1CSkIeA',
    appId: '1:613422672008:android:35cf1831d54b20fc25573d',
    messagingSenderId: '613422672008',
    projectId: 'xlcdapp',
    storageBucket: 'xlcdapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn1cvJBd0YeAn2jwFZUpq7srZo2qomTSI',
    appId: '1:613422672008:ios:7c5735d8ef3e17a325573d',
    messagingSenderId: '613422672008',
    projectId: 'xlcdapp',
    storageBucket: 'xlcdapp.appspot.com',
    iosClientId: '613422672008-nqlmbtekbddhh3pumrh7it8k7v1fnjch.apps.googleusercontent.com',
    iosBundleId: 'com.joyolord.xlcdapp',
  );
}
